### ISSUE TITLE
Des normes, des normes partout

### ISSUE THREAD

**Issue by ElsaVK** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#1]
Salut les filles :)
Il faudrait créer des normes de transcription pour notre projet. Notamment pour représenter:
- les mots que l'on ne réussit pas à transcrire
- les mots qu'on a transcrit à moitié
- les mots que l'on a transcrit mais dont on n'est pas sûre de la justesse de transcription
- les mots barrés, lisibles ou illisibles
- les dessins en marge
- question du rétablissement des majuscules ou non
- améliorer la lisibilité du rendu (ajout d'espaces entre le jour et la ligne, de tirets...)

Voilà, n'hésitez pas si vous pensez à d'autres points à éclairer :)
Elsa

**Comment by dtsoline** [comment]
Salut, 

Je propose : 

- 4 .  难 (nán pour difficile) pour les mots illisibles , 
- 1 . (_) pour les mots que l'on a pas réussi à lire, qui nécessitent une relecture tierce,
- 6 . concernant le rétablissement des majuscules, il serait nécessaire de se renseigner des normes en vigueur. 

Qu'en pensez-vous ?

Aussi, il me paraît également nécessaire de déterminer la manière de rendre compte des abréviations. A mon sens, le plus judicieux serait de transcrire uniquement les lettres qui sont écrites.

**Comment by AnaisMazoue** [comment]
Salut, 

En ce qui concerne les mots barrés, je vous propose qu'on utilise le signe 难 (nán) s'ils ne sont pas du tout lisibles, comme le suggère Soline mais qu'on les retranscrive s'ils sont lisibles. Qu'en dîtes-vous ?

**Comment by margauxfre** [comment]
Hello,

Bonne idée pour le caractère non latin ! Il faudrait utiliser le signe pour chaque caractère non lu, c'est bien cela ? Pour être plus claire, si le mot illisible comprend 5 caractères, on mettrait 5 fois le signe à la suite ? Et si il n'y a qu'un caractère illisible dans le mot, on le remplace par ce signe ?

Pour les mots incertains, est-ce que l'on pourrait mettre des [] plutôt que des () ? Cela permettrait d'éviter la confusion avec d'éventuelles () présentes dans le texte.

Pour les majuscules, je suis d'avis à respecter l'usage des majuscules du texte, puisque l'on souhaite établir une transcription et non une édition. Il me semble que le mieux soit de rester le plus fidèle au texte (et donc de ne pas non plus rétablir l'accentuation contemporaine).

On pourrait concentrer assez rapidement les décisions prises dans un read.me pour s'y référer facilement. Qu'en dites-vous ?

**Comment by ElsaVK** [comment]
Salut !

Suivant la proposition de @dtsoline nous utiliserons donc le caractère 难 pour les mots illisibles. Mais il y a une chose que je ne comprends pas, ce que souligne la question de @margauxfre : doit-on utiliser ce caractère à chaque fois que nous rencontrons un caractère illisible dans un même mot (exemple: "et ainsi dans la ch难el难难难le nous avons...") ou bien doit-on l'utiliser qu'une seule fois pour un mot à moitié illisible (même exemple: "et ainsi dans la 难 nous avons...") ?

Quelques exemples pour éclairer la situation:

Exemple 1:
![page8_opèrent](https://user-images.githubusercontent.com/92538363/143614458-2f15f5fc-6366-4e9d-acd3-195ba1eb523b.JPG) : ici, on finit par lire "opèrent" mais le mot est quand même raturé.
-> ma proposition pour ces cas: si le mot est raturé mais lisible, ne pas prendre en compte la rature et retranscrire le mot tel qu'on le lit, ici "opèrent". En gros, ce que tu as dit @AnaisMazoue 

Exemple 2:
![page8_terminé](https://user-images.githubusercontent.com/92538363/143614603-2d2f0a9b-55c5-466e-8ca1-7ab1a640a80c.JPG) : ici le "t" initial est mal tracé, car descend trop bas. On sent que Le Duc se reprend au milieu, mais son mot est lisible. 
-> ma proposition pour ces cas: on met de côté l'erreur d’inattention du Duc et on transcrit le mot lisible, ici "terminé".

Exemple 3:
![page9_19](https://user-images.githubusercontent.com/92538363/143614781-7b614f19-eb5c-429e-aa2e-cf5ccf0c5062.JPG) : le duc s'est trompé en écrivant une première fois le nombre du mauvais côté de la marge.
-> ma proposition dans ces cas: trouver un caractère qui en gros indiquerait "mot barré mais pas important".

Exemple 4:
![page9_illisible](https://user-images.githubusercontent.com/92538363/143614909-0f4d7055-0e2f-4a76-bd80-c2d010bbedee.JPG) : ici le mot est totalement illisible, pour ma part en tout cas...
- ma proposition pour ces cas: c'est ici qu'on utilise le caractère 难, mais seulement une fois, pour faire référence au mot dans son ensemble, même si on pouvait deviner une ou deux lettres.

Sinon pour les autres points, je suis d'accord avec @margauxfre pour mettre les mots incertains entre [] et non (). Ainsi que de respecter les majuscules et minuscules dans le texte.

Dernière chose: afin d'avoir l'esprit un peu plus clair, je vais créer un premier READ.ME sur la branche projetDN que vous pourrez modifier à votre guise. Question de commencer un peu à avoir un repère clair.

N'hésitez pas à me dire si je n'ai pas été claire.
A très vite tout le monde :)

**Comment by margauxfre** [comment]
Salut,

Pour répondre aux exemples de @CollapsarIsReal : je suis d'accord sur le traitement des cas 1 et 2, on favorise le mot final quand des lettres se superposent.
Pour les mots barrés, il faudrait trouver un moyen de les signifier, peut-être |19| ?
Le mot de l'exemple 4 me semble être "arcature" ?

N'hésitez pas à donner chacune votre avis sur les propositions, que les décisions puissent être validées collectivement :)
Et merci pour le readme Elsa!

**Comment by AnaisMazoue** [comment]
Bonjour les filles, 

Comme Margaux, j'approuve la solution d'Elsa pour les exemples 1 et 2. En ce qui concerne l'exemple 3, l'idée de Margaux me parait bonne, en plus je doute que le pipe soit un caractère utilisé dans les carnets de Viollet-le-Duc donc il ne devrait pas y avoir de problème de confusion. 

Je lis aussi "arcature" dans l'exemple 4 :)

Bonne journée à toutes !

**Comment by dtsoline** [comment]
Bonchour à toutes ! 

On n'a pas pris de décision ferme pour le traitement des abréviations : est-ce que la transcriptions des seules lettres écrites vous convient ?

**Comment by A-Menu** [comment]
Je suis d'accord avec les solutions de @CollapsarIsReal concernant les mots illisibles ; le pipe semble également être une bonne idée pour indiquer qu'un mot est raté mais lisible (cela ne risque cependant pas d'apprendre une mauvaise reconnaissance au modèle ?).

Concernant les abréviations, je pense qu'il est mieux ne pas les développer, ce projet étant de la transcription et non de l'édition. 

Qu'en pensez-vous ?

**Comment by margauxfre** [comment]
Si je ne me trompe pas : en mettant des pipes autour de chaque mot barré mais lisible, on apprend au modèle à reconnaître les mots de cette manière là. C'est donc un choix d'apprentissage pour indiquer à la machine comment transcrire les caractères barrés mais déchiffrables. Est-ce que vous aviez compris la même chose que moi ?

Je rejoins @A-Menu pour la gestion des abréviations.
