### ISSUE TITLE
Difficultés de transcription - page 3

### ISSUE THREAD

**Issue by AnaisMazoue** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#10]
Bonjour les filles, 

à mon tour de vous demander de l'aide pour quelques difficultés de transcription : 

1. continuation des travaux de charpente (pose des []
<img width="1002" alt="Capture d’écran 2021-12-08 à 16 10 16" src="https://user-images.githubusercontent.com/92513635/145238270-9c7b8bd7-0e50-4510-b89c-53db67ccfca7.png">

2. on [] le grattage des premieres travées de voutes du triforium
<img width="997" alt="Capture d’écran 2021-12-08 à 16 11 19" src="https://user-images.githubusercontent.com/92513635/145238295-b933dc8e-07a5-440e-b6f9-4c563081b8ee.png">

3. des [enduits] en pierre pour les [] du caveau des archevëques on
<img width="997" alt="Capture d’écran 2021-12-08 à 16 12 47" src="https://user-images.githubusercontent.com/92513635/145238342-044617be-71dc-40e5-904c-18892d8300d4.png">

4. morceaux de pierre formant [] dans les [] au dessus des [au] ogives
<img width="998" alt="Capture d’écran 2021-12-08 à 16 15 36" src="https://user-images.githubusercontent.com/92513635/145238371-08959380-621d-4473-a915-af59fd0216f3.png">

Merci à toutes :)

**Comment by margauxfre** [comment]
Bonjour Anaïs,

Ce que j'arrive à lire : 

2. "on continue"
3. peut-être "conduits" ?
4. dans les "tympans" au dessus des "arcs" ogives

Pour l'instant, je sèche sur les autres...

**Comment by AnaisMazoue** [comment]
Merci beaucoup, j'ajoute tout ça à ma transcription :)

**Comment by A-Menu** [comment]
Bonjour Anaïs, 

pour ma part : 

1. "pose des fermes et" (?)
2. Comme Margaux, "on continue"
3.  Je suis d'accord avec la suggestion "conduits" de Margaux ; je sèche pour le second mot
4. Je ne suis vraiment pas sûre pour celui-ci mais "formant voussure au dessous des arcs ogives" peut-être ?

**Comment by margauxfre** [comment]
Proposition pour la fin de la 1 "pannes" ? C'est une pièce de la charpente. 
Et pour la 4, peut-être "rampans" ? Pareil, le terme se retrouve lié à celui de "tympan" en architecture. Le "t" final aurait sauté mais ce n'est plus pas surprenant que ça pour la période... Mais je suis peut-être complètement à côté de la plaque !

**Comment by AnaisMazoue** [comment]
Merci beaucoup les filles, je vais ajouter tout ça à ma transcription :)
