### ISSUE TITLE
Difficultés - Page 4

### ISSUE THREAD

**Issue by dtsoline** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#11]
Bonjour à toutes !

A mon tour de demander de l'aide pour des mots quelque peu récalcitrants : 

1- On échafaude le deuxième bas coté de la nef nord pour le [reprirees]
![l27](https://user-images.githubusercontent.com/74775654/146010705-70c46031-9484-48e2-85fa-c8a8d7c34bc9.JPG)

2- On poursuit le [?age] des pénétrations et des noues du grand comble
![l37](https://user-images.githubusercontent.com/74775654/146009531-23f0800f-c9df-4cb1-be6b-85f9277a93f9.JPG)

3- On [] les deux figures dans les niches des contreforts [p?] de chaque
![l40](https://user-images.githubusercontent.com/74775654/146009616-6450e08a-9ab8-411b-bbe1-35e8d933b55e.JPG)

4- Suite des travaux de reprise des tympans au dessus des [??] [??] des deux
![l46](https://user-images.githubusercontent.com/74775654/146009689-defec6a8-a007-42fa-b379-01b6f29f55a9.JPG)

Si vous avez une idée !

**Comment by A-Menu** [comment]
Bonjour Soline,

de ce que j'arrive à lire : 

1. "le deuxième bas coté de la nef nord pour la reprise [ed]"
2. "le voligeage"
3. "on rajoute (?) les deux figures dans les niches des contreforts placés de chaque"
4. "des arcs ogives"

**Comment by margauxfre** [comment]
Je lis les mêmes choses qu'Ariane, pour compléter :
1. "pour la reprise **et**"

Le mot manquant en 3 ne me vient pas...

**Comment by dtsoline** [comment]
Merci à vous deux, j'ajoute cela à ma transcription :)
