### ISSUE TITLE
Transcription des ligatures

### ISSUE THREAD

**Issue by A-Menu** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#12]
Bonjour,

Il faudrait peut-être que l'on se mette d'accord sur la façon de transcrire les ligatures. Selon vous, faudrait-il les transcrire ligaturées, ou bien en caractères séparés ? 

Je pense en particulier au mot "chœur", qui est assez récurrent dans le texte. Faut-il donc le transcrire en tant que "chœur" (avec la ligature) ou bien "choeur" (sans) ?

Cordialement,

**Comment by margauxfre** [comment]
Bonjour Ariane,

C'est vrai qu'il va falloir faire attention à ce point ! Merci !
Pour ma part, j'ai transcrit avec les ligatures (chœur) mais peut-être n'avons-nous pas toutes fait pareil ?
On peut en discuter :)

**Comment by A-Menu** [comment]
Cela me semble également être la meilleure solution, je vais de ce pas vérifier mes transcriptions.

Je laisse l'issue ouverte pour le moment pour être sûre que tout le monde rejoint cette transcription.

**Comment by AnaisMazoue** [comment]
Bonjour les filles, 

J'ai également transcrit ainsi : chœur mais si vous trouvez plus logique de séparer le e et le o, je le changerai sur mes transcriptions :)

**Comment by dtsoline** [comment]
Bonjour les filles ! 

Pour ma part, au contraire, je ne les ai pas transcrites puisqu'il n'a pas accentué ses ligatures et donc pour rester, à mon sens, au plus près de ce qui est écrit.

**Comment by margauxfre** [comment]
Coucou, 

de mon côté, j'ai l'impression que les ligatures sont plutôt respectées :
![Capture d’écran 2022-01-07 à 16 50 03](https://user-images.githubusercontent.com/92535159/148570055-814d9e37-1960-4a5a-9530-1ae64488e774.png)
 ![Capture d’écran 2022-01-07 à 16 49 50](https://user-images.githubusercontent.com/92535159/148569974-da2aadea-ae44-46cc-9f73-020ba59afd9a.png)

et vous ?

**Comment by A-Menu** [comment]
J'aurais tendance à dire comme @margauxfre

**Comment by AnaisMazoue** [comment]
Je suis du même avis que @margauxfre et @A-Menu, il me semble que les ligatures sont plutôt respectées :)

**Comment by margauxfre** [comment]
Après en avoir discuté toutes ensemble, la ligature l'emporte :) je ferme l'issue et le rajoute dans les normes de transcriptions !
