### ISSUE TITLE
Difficultés de transcription - page 6

### ISSUE THREAD

**Issue by A-Menu** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#13]
Bonjour à toutes (et bonnes fêtes de fin d'année),

Je viens à mon tour demander de l'aide pour quelques mots récalcitrants : 

1. Ce mot est régulièrement retrouvé sur mes deux pages mais son épellation m'échappe. Au vu du contexte je pense à un mot similaire à "côté", mais cela ne correspond pas. 

<img width="928" alt="1" src="https://user-images.githubusercontent.com/92547721/147408883-3d84b9e8-8099-4ceb-b8eb-b72e6b64daa0.png">
<img width="929" alt="1 bis" src="https://user-images.githubusercontent.com/92547721/147408892-11769117-63e1-48a9-b67a-fa0d916fe635.png">
<img width="932" alt="1 qu" src="https://user-images.githubusercontent.com/92547721/147408895-8e81bec5-4480-4848-9e60-3b2aed4924f1.png">
<img width="932" alt="1 ter" src="https://user-images.githubusercontent.com/92547721/147408894-9a5ce5e1-854c-4216-835c-51a368be8c62.png">

2. Deuxième mot : 

<img width="927" alt="2" src="https://user-images.githubusercontent.com/92547721/147408911-eee0172d-dd7a-4665-931b-bdbcad35c0ee.png">

3. Plusieurs difficultés sur une même phrase : 
<img width="932" alt="Capture d’écran 2021-12-26 140718" src="https://user-images.githubusercontent.com/92547721/147409043-d263639c-1be8-403a-b61b-7d5b6678b4f0.png">
<img width="928" alt="3 bis" src="https://user-images.githubusercontent.com/92547721/147408940-c7c5557a-cf86-4bcc-a4b7-d0e0cd7c20f7.png">
<img width="913" alt="3 ter" src="https://user-images.githubusercontent.com/92547721/147408943-059658d8-2473-486b-be3f-08649ef4b34a.png">

4. Il semblerait que ce soit le même mot, mais j'ignore lequel (ravalement ? renouvellement ?)
<img width="927" alt="4" src="https://user-images.githubusercontent.com/92547721/147408960-73875176-2add-49ad-92ba-a503ed1eb543.png">
<img width="928" alt="6" src="https://user-images.githubusercontent.com/92547721/147408975-4451fe4c-6d05-49ec-84ca-7322b16bdea4.png">

5. "Entretien" peut-être ?
<img width="923" alt="5" src="https://user-images.githubusercontent.com/92547721/147408971-e593ab71-d33b-45f9-8eed-19e9aa3af816.png">

6. Enfin, encore plusieurs difficultés sur une même phrase : 
<img width="932" alt="7" src="https://user-images.githubusercontent.com/92547721/147408980-569abab0-9dee-42ea-8991-c3d16b0c6eed.png">
<img width="931" alt="7 bis" src="https://user-images.githubusercontent.com/92547721/147408986-165f4d78-8ff3-42e9-9e75-42365943b2eb.png">

7. Enfin, j'ai du mal à deviner le numéro utilisé en deuxième ligne ici. Je lis "Juin 2 / ?? / 9 / 11"
<img width="244" alt="page 6" src="https://user-images.githubusercontent.com/92547721/147409325-95fcf0dd-729e-4ecf-bc10-620a7cef69dd.png">

Navrée pour ces nombreuses questions et merci d'avance !

**Comment by dtsoline** [comment]
Bonjour !
Je n'ai pas d'idée pour les autres mais pour la 7., il s'agit pour moi d'un 5.
Le mot dans la 6. revient à plusieurs reprises dans mon extrait aussi, je ne le trouve pas non plus...


Edit : Pour la 5., je pencherais pour " les noues formées par l'intersection des combles" mais sans certitude !

**Comment by A-Menu** [comment]
Merci beaucoup Soline, je vais modifier la transcription de ce pas !

**Comment by margauxfre** [comment]
1. C'est vrai que le mot semble assez fréquent et on en a plein d'exemples mais rien ne me vient non plus... On va bien réussir à trouver !
2. "celle" ?
3. "les" et "les députations etc"
4. "raccordement" (le premier au pluriel et le second au singulier"
5. "par l'intersection"
6. "par incrustement" et "jointoiement"
7. "5"

Voilà ce que je dirais !

**Comment by A-Menu** [comment]
Merci beaucoup Margaux pour ton aide précieuse !
