### ISSUE TITLE
Difficultés de transcription - page 7

### ISSUE THREAD

**Issue by A-Menu** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#14]
Rebonjour à toutes,

Après celles de la page 6, voici les difficultés de la page 7 : 

1. Le problème porte ici sur le premier mot entre crochets (le second étant traité en 1. de l'issue concernant la page 6)
<img width="929" alt="1" src="https://user-images.githubusercontent.com/92547721/147409405-ad6fbcad-a972-4a44-badb-81fee03cb718.png">

2. Cette phrase commence par "on continue a déposer l'ancienne charpente de la nef dans la première" et se poursuit ainsi :
<img width="926" alt="2" src="https://user-images.githubusercontent.com/92547721/147409410-211b05de-341f-4b81-84e5-cfe0d39340a0.png">

3. 
<img width="925" alt="3" src="https://user-images.githubusercontent.com/92547721/147409417-9922fb33-5c32-4577-9eac-91c393839410.png">

4. 
<img width="938" alt="4" src="https://user-images.githubusercontent.com/92547721/147409419-550fdab9-6e56-4423-9f4d-ebe8bb38a31b.png">

5. 
<img width="928" alt="5" src="https://user-images.githubusercontent.com/92547721/147409432-ded065ac-1b0c-46bc-99c5-d47c3cfc8e14.png">

6. Et pour terminer, quelques difficultés rencontrées dans une même phrase : 
<img width="925" alt="6" src="https://user-images.githubusercontent.com/92547721/147409447-395d595b-4aef-43f1-9fa0-2274a65cc323.png">
<img width="920" alt="6 bis" src="https://user-images.githubusercontent.com/92547721/147409449-9e55d23d-9a7f-448f-90de-d916dbc778f0.png">

Merci d'avance !

**Comment by dtsoline** [comment]
Bonjour, pour la 4 je dirais bien " les curseurs dorés sur [] en marbre satiné".

**Comment by margauxfre** [comment]
1. je lis également "imprimer"
2. qui "avoisine" ?
3. je lis "décorent" aussi mais ça ne fait pas grand sens avec le mot d'après...
4. "cristaux" ?, "piédestaux", "destinés"
5. "pour ces mêmes chapelles"
6. Je sèche...

**Comment by A-Menu** [comment]
Merci beaucoup pour votre aide Soline et Margaux !
