### ISSUE TITLE
Difficultés de transcription - page 5

### ISSUE THREAD

**Issue by dtsoline** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#15]
Bonjour à toutes ! 

Quoi de mieux que de retrouver eScriptorium pour un bon début d'année ? J'aurai besoin d'aide pour les lignes suivantes :

![l30](https://user-images.githubusercontent.com/74775654/147942620-a01a7e5f-4bcc-42d2-8f28-d339fc2fe828.JPG)
![l48](https://user-images.githubusercontent.com/74775654/147942624-7ee3016b-b87b-43ee-829b-49f4a0298bd7.JPG)
![l49](https://user-images.githubusercontent.com/74775654/147942625-7578ce87-cd7f-4bd2-9fe2-13b7e6b8f4f3.JPG)
![l5](https://user-images.githubusercontent.com/74775654/147942626-650ae422-87c3-4082-a41a-ad90db049e98.JPG)
![l6](https://user-images.githubusercontent.com/74775654/147942629-903b0b26-40ea-46c4-9106-dc8e3d14c6b3.JPG)
![l17](https://user-images.githubusercontent.com/74775654/147942631-965d6557-46eb-4a24-91fc-24a0d1dd1915.JPG)
![l21](https://user-images.githubusercontent.com/74775654/147942632-f97b08f7-0014-4a00-af35-62fc1e3589e4.JPG)
![l29](https://user-images.githubusercontent.com/74775654/147942635-706f0fd0-922f-4122-9f3a-cb87bad89ff6.JPG)

Si vous avez idée, je suis preneuse ! 

Merci à toutes

**Comment by margauxfre** [comment]
Salut Soline,

Mes propositions :
ligne 5 : je suis d'accord pour le "pose" et ?
ligne 6 : je lis la même chose que toi. 
ligne 17 : "diagonaux"
ligne 21 : "incrustement" ? 
ligne 29 : arcs "diagonaux" et "doubleaux"
ligne 30 : "chainages"
ligne 48 : je pense que c'est "bander". Si on se reporte au _Dictionnaire général des termes d'architecture_ de Daniel Ramée, disponible ici : [https://gallica.bnf.fr/ark:/12148/bpt6k62498574](url), on a la définition page 40 : "Serrer les claveaux et la clef d'une voûte, d'un arc ou d'une plate-bande". Le dictionnaire est assez pratique pour vérifier les termes d'architectures, en plus on peut chercher directement dans l'OCR ! :)
ligne 49 : "diagonaux" également

**Comment by ElsaVK** [comment]
Salut :)
Margaux a très bien répondu et trouvé beaucoup plus de mots que moi. Les lignes 21 et 30 me laissent en échec...Merci Margaux pour le dictionnaire, très pratique !

**Comment by A-Menu** [comment]
Bonjour Soline, 

Je rejoins les transcriptions proposées par Margaux ; j'ajoute que pour la ligne 48, le deuxième mot à trouver est "doubleaux".

Je sèche pour le deuxième mot de la ligne 5 et pour la ligne 21..

**Comment by AnaisMazoue** [comment]
Salut Soline, 
Pour le deuxième mot de la ligne 5, je dirais peut-être "cercles" mais je sèche également pour la ligne 21..

**Comment by dtsoline** [comment]
Merci à toutes !!
