### ISSUE TITLE
Un problème de tableau

### ISSUE THREAD

**Issue by dtsoline** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#16]
Bonjour à toutes, 

On en avait parlé au commencement du projet sans en poser une réelle réponse, j'ai une interrogation quant au traitement des tableaux dans le document même si je crois qu'il y en a qu'un pour 1860. 
Comment on en définit les zones ? 
Pour le moment j'ai créée une zone "texte" différente pour le séparer du reste du texte mais cela me semble un peu artificiel, sinon peut-être l'intégré sans distinction au corps du texte ? Ou alors définir une zone spécifique pour les tableaux ?

Qu'en pensez-vous ?

**Comment by AnaisMazoue** [comment]
Coucou Soline, 
Je pense qu'on peut créer une zone tableau, elle-même intégrée à la zone main (un peu comme ce que l'on a fait avec la zone illustration dans la zone marge). Qu'en dites-vous ?

**Comment by margauxfre** [comment]
Salut,
Je pense qu'on peut suivre l'idée de @AnaisMazoue ! On créerait une zone "tableau" sur eScriptorium.
Si ça convient à tout le monde !

**Comment by ElsaVK** [comment]
Je trouve ça très bien aussi :)

**Comment by A-Menu** [comment]
Oui faisons comme ça !

**Comment by dtsoline** [comment]
Parfait ! Je clos l'issue si tout le monde est d'accord :)
