### ISSUE TITLE
Difficultés de transcription - page 9

### ISSUE THREAD

**Issue by ElsaVK** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#19]
Bonsoir à toutes :) 
J'aurais besoin d'un peu d'aide sur cette page:

1)
![page_9_l30](https://user-images.githubusercontent.com/92538363/148420493-9467816f-665c-4b52-8bb1-00d731c2a55d.png)

2)
![page_9_l44](https://user-images.githubusercontent.com/92538363/148420520-1c57768c-3d7d-4cbf-a6a9-f7575cfaba3c.png)

3)
![page_9_l50](https://user-images.githubusercontent.com/92538363/148420547-ea1727d2-641a-447b-be93-2dae7e6ef2e1.png)

4)
![page_9_l55](https://user-images.githubusercontent.com/92538363/148420588-9ddad994-1397-4964-adaf-1d4231531b77.png)

5)
![page_9_l57](https://user-images.githubusercontent.com/92538363/148420615-6381ef2c-8305-41da-83dc-90ab542d3d4e.png)

Merci !

**Comment by margauxfre** [comment]
Salut,

ce que je lis :
1. « voussures »
2. « chevronnage »
3. Je dirais « rejointoiement », le mot revient plusieurs fois dans nos pages. Par contre, dans ton cas, est-ce vraiment un « o » après le « t » ? 
Cela me fait penser qu’on pourrait peut-être créer une liste du vocabulaire architectural quelque part ? 
4. « ogives »
5. « ce même »

**Comment by ElsaVK** [comment]
Oooooh la super idée pour créer la liste de vocabulaire !! A faire !
Et merci pour les réponses :)
