### ISSUE TITLE
découpage des zones (et début de la problématique de numérotation des lignes)

### ISSUE THREAD

**Issue by margauxfre** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#2]
Bonjour à toutes,

Suite à notre réunion, nous avons décidé de découper chaque page en 4 zones : 
- la zone principale qui constitue le corps du texte (à nommer main sur eScriptorium)
- une zone marge (marge)
- une zone pour encadrer les illustrations (Illustrations)
- une zone pour délimiter le numéro de folio (folio)

Voici un exemple de ce que cela donnerait sur une de mes pages. Est-ce que vous arrivez à quelque chose de similaire ? Le découpage vous parait cohérent ?

![Capture d’écran 2021-11-24 à 16 22 31](https://user-images.githubusercontent.com/92535159/143266778-a7a5869f-aec9-4679-9064-0a28c071de5a.png)

**Comment by ElsaVK** [comment]
Salut !
Super idée l'illustration, les consignes sont très claires comme ça ! Pour ma part je suis tout à fait d'accord avec cette manière de procéder :) lets'go !
Edit: petite question: comment fais-t-on pour numéroter les lignes dans le bon ordre du coup ? Elles ne vont pas se lire une zone après une autre ? Or nous voulions que la ligne qui indique un jour soit suivie dans la numérotation par la ligne qui décrit ce qui a été fait dans la journée. J'espère être claire...

**Comment by margauxfre** [comment]
Personnellement, elles ne se numérotent pas une zone après l'autre mais plutôt selon leur position dans la page. J'ai l'impression qu'il faut parfois jouer un peu sur la hauteur des ligne pour récupérer le bon ordre entre le jour et le début du texte auquel il correspond, peut-être avez vous une technique ? Mais dans la plupart des cas, ça fonctionne tout seul !

Exemple :
![Capture d’écran 2021-12-02 à 17 07 36](https://user-images.githubusercontent.com/92535159/144458921-933ebabd-ebd8-45c7-9108-157c51382604.png)

Edit : ou sinon peut-on considérer de créer une ligne continue entre le jour et le texte ? Peut-on créer une ligne inter-zone ?

**Comment by AnaisMazoue** [comment]
J'ai l'impression que la numérotation est assez correcte également dans ma partie, avec seulement quelques petits ajustements à faire. 

Je suis d'avis à laisser une numérotation distincte par colonnes car parfois la date est légèrement décalée par rapport au texte de la partie droite de la page et donc pas exactement sur la même ligne. Dans ce dernier cas, je ne sais pas dans quelle mesure il serait possible de faire une ligne qui ne serait pas vraiment droite... Nous pouvons bien sûr en discuter afin d'être bien toutes d'accord :)

**Comment by dtsoline** [comment]
De mon côté, la numérotation automatique est assez incohérente et ne correspond pas à la disposition sur la page :
![probleme ligne](https://user-images.githubusercontent.com/74775654/144716389-bafee91f-c8c2-4fb6-b9b6-390c4a0beca3.JPG)
Avez-vous une idée de la manière selon laquelle procéder pour remédier à cela ? 

Aussi, je suis également d'avis de laisser une ligne différente pour la date dans la marge et dans le corps du texte. 

En outre, concernant le découpage des zones, faut-il couvrir l'ensemble de la page (comme sur la capture ci-dessous) ou bien s'en tenir au zones où se trouve du texte ?
![marge escriptorium](https://user-images.githubusercontent.com/74775654/144716570-0fbc86a0-2a6f-4a3f-b774-1b78a3777e74.JPG)
 
PS: je viens d'ajouter le détail d'application des zones dans eScriptorium dans le readme !

**Comment by AnaisMazoue** [comment]
Ayant fait quelques corrections sur eScriptorium, je me rends compte que la numérotation des lignes n'est plus si cohérente non plus sur mes pages mais je ne sais pas non plus comment régler ce problème. 

Toujours sur cette question de numérotation, j'ai quelques autres questions : 
- la ligne 1 est-elle toujours celle du numéro de la page ? 
- dans le même ordre d'idée, la ligne 2 correspond-elle toujours à 1860 ? ou bien est-ce qu'on privilégie la ligne de texte si il s'agit de la fin du paragraphe de la page précédente comme ici ? 

<img width="573" alt="Capture d’écran 2021-12-06 à 14 57 29" src="https://user-images.githubusercontent.com/92513635/144859379-367d588e-88c2-4bc8-a8e2-096d9a9073c4.png">

-en s'appuyant encore sur la photo au-dessus, faites-vous une ligne pour "Janvier" et une pour "30" ou bien une seule ligne "Janvier 30" ? 
- comment numéroter les ajouts en interligne ? 
- qu'en est-il pour le texte ajouté en marge ?  

Au sujet du découpage des zones, je trouve que couvrir l'ensemble de la page est une bonne idée !

**Comment by A-Menu** [comment]
- J'avais cru comprendre que la numérotation se faisait selon l'ordre de la page, en partant de la partie supérieure gauche. Sur l'image postée par Soline, on aurait ainsi "331" en 1, "1860" en 2, la première ligne de texte en 3, "Janvier 30" en 4, etc. 

- Concernant les lignes en marge, j'ai rassemblé "Janvier 30" en une seule ligne, mais cela est modifiable si l'on décide de séparer en "Janvier" et "30". 

- Pour les ajouts en interligne, nous pouvons l'intégrer dans la numérotation en suivant l'ordre de la page. Ainsi, un interligne entre les lignes 5 et 6 donnera au final "ligne 5", "ligne 6" (interligne), "ligne 7".
- Je suppose qu'il faudrait également suivre l'ordre de la page (et non du texte) en cas de texte ajouté en marge ? (aux dépends de la lecture cependant).

- Je retrouve les mêmes problèmes de numérotation de lignes ; j'ignore pour le moment comment y remédier.

**Comment by margauxfre** [comment]
Je vous rejoins finalement sur le problème de numérotation des lignes... J'ai renommé le titre de l'_issue_ mais peut-être préféreriez-vous en ouvrir une nouvelle consacrée à la gestion de cette numérotation ? Il y a visiblement pas mal à discuter dessus...

Pour le découpage des zones, c'est une bonne idée de couvrir l'ensemble de la page, surtout qu'on pourrait potentiellement trouver de l'écriture n'importe où sur les pages du cahier ! Inclut-on donc le numéro de folio dans la zone main ou marge (exemple de @dtsoline) ou commence-t-on la zone main juste en dessus du folio (ce qu'a fait @AnaisMazoue) ?

**Comment by ElsaVK** [comment]
@margauxfre pour répondre à ta question concernant le numéro de folio, j'ai fait de mon côté comme Soline car je trouve que ça permet de recouvrir la page entièrement en zones, ce que ne permet pas le modèle d'Anais.

Pour ce qui est de la numérotation des lignes je propose d'ouvrir une issue supplémentaire afin de ne pas gérer trop de problèmes à la fois dans cette issue. Je m'occupe de la créer ;)

**Comment by margauxfre** [comment]
Ca marche ! Je vais modifier les délimitations de mes zones pour les aligner avec les vôtres :)

Merci @CollapsarIsReal pour l'issue !

**Comment by AnaisMazoue** [comment]
J'ai également modifié le découpage des zones sur mes pages afin que l'ensemble soit cohérent :)
