### ISSUE TITLE
Partage des relectures

### ISSUE THREAD

**Issue by margauxfre** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#20]
Coucou les filles,

Où en êtes-vous dans vos transcriptions ? Je me demandais si on pouvait passer aux relectures. On pourrait se répartir les pages à relire : on avait parlé du fait qu’une personne relise le travail d’une autre personne.

en tout cas, mes transcriptions sont prêtes à la relecture si quelqu’un veut se lancer :)

On pourra par la suite mettre la répartition dans le readme, non ?

**Comment by ElsaVK** [comment]
Génial ! Perso mes deux pages (8 et 9) sont aussi prêtes à la relecture. Je te propose qu'on se relise l'une et l'autre mutuellement ? Pour ce qui est du reste du groupe, on peut peut-être attribuer au hasard ? Si je dis @dtsoline relit @A-Menu , @A-Menu relit @AnaisMazoue qui elle même relit @dtsoline , ça irait à toutes ?
Et ok pour le spécifier dans le readme :)

**Comment by ElsaVK** [comment]
EDIT: Attends je viens de me rendre compte que mes dossiers étaient en zip, je vais les dezipper et renommer mes fichiers pour que ça colle au readme. Je te dis quand c'est bon :)

**Comment by margauxfre** [comment]
Super, j'attends ton feu vert donc ! et le partage me convient tout à fait :)

**Comment by A-Menu** [comment]
Ça marche pour la répartition ! 

Je te tiens au courant @dtsoline  :)

**Comment by AnaisMazoue** [comment]
La répartition me convient aussi. De mon côté, la transcription est finie, je n'ai plus qu'à numéroter correctement les lignes et @A-Menu tu pourras passer à la relecture quand tu voudras :)

**Comment by ElsaVK** [comment]
@margauxfre Ca y'est, je lance officiellement l'heure des relectures ! Mes deux fichiers sont prêts (et sauvegardés en local donc pas de soucis), tu peux les relire Margaux ;) Je m'excuse déjà pour la page 8, y'a beaucoup de mots où je ne suis pas du tout sûre de moi...En tout cas, merci à toi !

**Comment by margauxfre** [comment]
Super @CollapsarIsReal ! Je m’y mets de ce pas :)

**Comment by dtsoline** [comment]
Parfait pour la répartition, merci Elsa !

**Comment by A-Menu** [comment]
Bonjour @dtsoline , pour information mes deux pages sont prêtes pour la relecture :)

**Comment by dtsoline** [comment]
@A-Menu super, je m'y mets ! les miennes sont également prêtes :)
