### ISSUE TITLE
Ajouts possibles au projet

### ISSUE THREAD

**Issue by dtsoline** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#22]
Salut ! 

Je me demandais s'il ne serait pas utile d'ajouter les fichiers en texte brut afin d'avoir une version plus facilement lisible après les relectures. 
En outre, le "dictionnaire" pourrait peut-être se trouver dans un dossier markdown regroupant l'image du mot et sa définition ?

Qu'en pensez-vous ?

**Comment by A-Menu** [comment]
Coucou ! 

Bonnes idées ! 
- Le relecteur pourrait générer ce texte et l'ajouter en même temps que l'xml relu. 
- Quant au dictionnaire, je vais de ce pas le créer

**Comment by margauxfre** [comment]
Super !
Comme les relectures sont déjà faites pour Elsa, @CollapsarIsReal penses-tu pouvoir te charger d'ajouter le texte brut directement sur ta branche ?

**Comment by AnaisMazoue** [comment]
Très bonnes idées Soline ! Je vais indiquer dans le README qu'il y a également un fichier correspondant au texte brut de chaque page :)
