### ISSUE TITLE
Nom des fichiers

### ISSUE THREAD

**Issue by AnaisMazoue** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#3]
Bonjour à toutes, 

Il faudrait probablement qu'on se mette d'accord sur la manière de nommer les fichiers xml qui correspondent aux différentes pages. Je vous propose NDP_page01, qu'en pensez-vous ?

**Comment by ElsaVK** [comment]
Faisons comme cela si ça convient aux autres aussi :) Si c'est le cas, pensez à modifier le nom de vos anciens et futurs fichiers avant de les push.

**Comment by margauxfre** [comment]
Parfait pour moi !

**Comment by dtsoline** [comment]
Oui ça me paraît très bien également !

**Comment by A-Menu** [comment]
C'est entendu !
