### ISSUE TITLE
nom du dépôt

### ISSUE THREAD

**Issue by margauxfre** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#34]
Hello Soline,

Avant de rendre le projet, il faudrait penser à nommer le dépôt selon la norme fournie dans la consigne. Comme tu en es la propriétaire, pourrais-tu t'en charger, s'il-te-plait ?

Merci :)

**Comment by A-Menu** [comment]
Et si je comprends bien il faut le nommer "TNAH-2021-Projet-Notre-Dame".

**Comment by dtsoline** [comment]
Je m'en occupe
j'ai compris pareil Ariane !
