### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by stweil** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#38]
I just discovered your nice project while looking for other transcriptions which were created using eScriptorium (I just uploaded one myself: https://github.com/UB-Mannheim/DTGT) and noticed that there is currently no license specified.

I'd like to add your data to https://cneud.github.io/ocr-gt/, and for that it would be good to know the license.

Merci,
S. W.

**Comment by A-Menu** [comment]
Hello, and thank you for your interest in the project! 

As shown in the [htr-united.yml](https://github.com/PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame/blob/main/htr-united.yml) file (line 46), the data is available under a [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) license, so feel free to use it ! 

Have a nice day,
A. M.

**Comment by stweil** [comment]
Merci bien. Maybe you want to add a `LICENSE` file nevertheless. Then GitHub will show the license automatically.

See for example https://github.com/UB-Mannheim/DTGT.
