### ISSUE TITLE
Relecture des transcriptions

### ISSUE THREAD

**Issue by margauxfre** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#4]
Hello,

Je pense que ça serait intéressant que les transcriptions soient relues par un oeil différent de celui du transcripteur.
On pourrait partir directement de l'état des fichiers sur eScriptorium (puisque l'on a toutes accès à l'ensemble du fichier).
Chacune pourrait relire les pages transcrites par une autre personne. Qu'en pensez-vous ?

**Comment by ElsaVK** [comment]
Hey !
Dans ce cas pas la peine de forker les branches de chacune si j'ai bien compris ? On part directement du fichier sur eScriptorium, qu'on importe en xml puis qu'on ajoute sur la (nouvelle) branche "Relectures" (qu'une d'entre nous sera la première à créer) sur Github ?
Edit: Il ne faut pas oublier de laisser le temps à chacune de terminer et relire la transcription de ses pages. Prévenez dès que vous êtes prêtes à faire relire votre travail :)

**Comment by margauxfre** [comment]
Salut !

Je suis d'accord pour la manière de procéder ! Tu as raison, si ça convient à tout le monde, il faudra bien penser à se donner le feu vert et s'assurer que chacune a bien mis ses dernières versions des fichiers sur sa branche avant de commencer les relectures. On pourra aussi penser à une répartition quand on sera prêtes.

**Comment by AnaisMazoue** [comment]
Hello !

Je suis d'accord avec vous pour poursuivre notre travail de cette manière ! De mon côté, je pense que je devrais avoir terminé ma transcription au cours de la semaine prochaine.

**Comment by A-Menu** [comment]
Bonjour,

Oui, cela semble être une bonne idée ! Faut-il selon vous annoncer le feu vert pour une relecture via une issue, afin de lui donner en visibilité ?

**Comment by margauxfre** [comment]
Bonne idée @A-Menu ! :) On pourra se les répartir facilement comme ça.

**Comment by ElsaVK** [comment]
Ca me va aussi !
