### ISSUE TITLE
Organisation des branches

### ISSUE THREAD

**Issue by margauxfre** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#6]
Bonjour les filles,

Je ne sais pas si vous trouverez mon issue nécessaire mais je me demandais comment on pourrait organiser nos branches de manière à ce que leur contenu soit présenté de manière identique d'une branche à l'autre.
On a déjà décidé une façon de nommer les fichiers mais chaque branche est organisée différemment : soit les fichiers sont envoyés directement sur la branche, soit ils sont inclus dans un dossier. 
On s'y retrouve bien sûr mais peut-être que l'on pourrait faire quelque chose de plus harmonieux ?

Deux propositions : 
- on crée un dossier par page afin d'y glisser à la fois le fichier .xml qui contient la transcription et le fichier image .png (qui se télécharge depuis eScriptorium quand on choisit de récupérer l'image à l'export).
- on met directement les fichiers sur la branche en .xml et .png

A voir aussi pour la suite :  il faudrait penser à la question des relectures que l'on déposera sur nos branches. Dans ce cas, peut-être faudrait-il créer un dossier pour les transcriptions et un dossier pour les relectures ?

J'espère que c'est clair, dites-moi !

**Comment by A-Menu** [comment]
Salut, 

Peut-être que faire un dossier par page serait plus clair ? Puis dans chaque dossier de page (nommé par exemple "page_7"), on pourrait y retrouver un dossier "transcription" et un dossier "relectures". Une option avec moins de dossiers peut également être utilisée cependant.

Pour rebondir sur l'organisation des branches, pensez-vous qu'un seul fichier png par dossier soit suffisant ? (étant donné qu'il ne se modifie pas au fil du temps). Si oui, faut-il l'insérer à la fois dans le dossier "transcriptions" et le dossier "relectures" ?

**Comment by ElsaVK** [comment]
Salut !

Donc si je suis bien, il nous faudrait des "dossiers par page" dans lequels on retrouverait un dossier "transcription" ainsi qu'un autre "relecture" ? J'ai peur que cela fasse un peu beaucoup. Car dans la logique, on crée un dossier dans l'optique de regrouper plusieurs fichiers dedans. Or, dans nos dossiers "transcription" il n'y aura que deux fichiers: "NDP_page08" qui est mis à jour à chaque push et l'image png qui ne va pas bouger (comme tu dis Arianne, ça ne sert à rien de la réupload à chaque fois)? Pareil pour le dossier "relecture" qui n'aura qu'un seule version mise à jour par nous toutes (ce qui nous permettra en plus de travailler sur la gestion de conflits). Donc ne vaudrait-il pas mieux plutôt d'avoir un "dossier par page" dans lequel on retrouve directement nos trois fichiers "image", "transcription" et "relecture" ?

En résumé:
Est-ce qu'on préfère la première version :
![Capture d’écran de 2021-12-06 23-12-40](https://user-images.githubusercontent.com/92538363/144931399-7d9f0008-afe8-4e02-8db1-92544fde6346.png)

Ou bien la deuxième :
![Capture d’écran de 2021-12-06 23-14-29](https://user-images.githubusercontent.com/92538363/144931488-98dcf295-bab0-4a6a-8e72-f3a3bc88cd9a.png)

**Comment by A-Menu** [comment]
Ou sinon pour éviter d'avoir trop de dossiers / fichiers par branche (d'autant plus que ça nous amènerait à aller travailler sur les branches des autres), on peut régler ça de la même manière qu'on gère nos problèmes de transcription, à savoir : 

- Dès que qu'une personne estime que sa page est prête pour relecture, elle fait une issue pour le signaler.
- Les autres sont alors libres d'aller voir sur eScriptorium la transcription proposée, et s'il y a des modifications à faire, on peut les indiquer en réponse à l'issue.
- Pour terminer, la personne à l'origine de l'issue corrige sa transcription et met à jour le dépôt github

Avec cette méthode, on pourrait avoir des dossiers prenant la forme de la 2e option proposée par @CollapsarIsReal (sans le fichier NDP_pg08_relec.xml)

**Comment by margauxfre** [comment]
Ta proposition @A-Menu me semble être une bonne solution ! Cela permettrait de soumettre les modifications à validation de l'ensemble du groupe. Chaque relecteur prendrait une capture d'écran de la partie à modifier et les posterait sur l'issue pour approbation. Est-ce bien cela ?

Par ailleurs, il faudrait également penser à nommer le fichier image selon le numéro de page : NDP_page08.png par exemple.

**Comment by AnaisMazoue** [comment]
Je comprends comme toi @margauxfre et je pense que c'est une bonne idée qui devrait nous permettre de nous y retrouver facilement mais sans multiplier les fichiers et/ou dossiers. 

Cette manière de nommer les fichiers image ma parait tout à fait bien :)

**Comment by margauxfre** [comment]
Coucou les filles,

Est-ce que l'on valide cette idée ? Que l'on puisse réorganiser chacune notre branche dès le feu vert :)

**Comment by A-Menu** [comment]
Coucou Margaux, je valide pour ma part !

**Comment by AnaisMazoue** [comment]
C’est aussi bon pour moi, bonne fin de journée à toute :)
