### ISSUE TITLE
Difficultés de transcription - page 8

### ISSUE THREAD

**Issue by ElsaVK** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#8]
Bonjour à toutes :)

Je m'excuse par avance pour le nombre de mots qui m'ont posé des difficultés... En revanche, j'espère beaucoup que vous pourrez m'éclairer sur ces points !

1) "echafaudages légers [??] [??] du grand comble pour la plomberie des"
![Capture d’écran de 2021-12-06 22-04-01](https://user-images.githubusercontent.com/92538363/144923593-3e0554be-54e1-46cc-ac6a-308bd42350e9.png)
 
2) "quatre grandes contrefiches de la flèche formant [gradins] 难  destinés à recevoir"
![Capture d’écran de 2021-12-06 22-06-13](https://user-images.githubusercontent.com/92538363/144923694-e289d141-90d7-4535-af9e-c9528eaa43f7.png)

"de la flèche formant [gradins] dans les [revues] des combles. pose des verrières"
![Capture d’écran de 2021-12-06 22-09-58](https://user-images.githubusercontent.com/92538363/144924701-41856c83-fdad-4da1-923f-f78baa1bf1bf.png)

3) (Celui-ci je le retrouve plein de fois dans le texte) "les travaux de charpente et de [??] se poursuivent sur le grand comble"
![Capture d’écran de 2021-12-06 22-06-41](https://user-images.githubusercontent.com/92538363/144923783-8e45c9e5-65a7-44e2-b1a1-cd0a6a0821b4.png)

"le [??] sur la travée de charpente au dessus de la nef. 难 les plombiers"
![Capture d’écran de 2021-12-06 22-07-45](https://user-images.githubusercontent.com/92538363/144924188-40d3136c-aeaa-4972-b7a5-14ac0b41036f.png)

"le [??] de la travée de charpente au dessus de la 1ere travée du choeur est terminé"
![Capture d’écran de 2021-12-06 22-07-36](https://user-images.githubusercontent.com/92538363/144924029-320320cc-25b1-4430-8afc-b0def0000de9.png)

4) "on a [apres] [??] [??] les [parties] de tapisserie au dessus des [??]"
![Capture d’écran de 2021-12-06 22-07-08](https://user-images.githubusercontent.com/92538363/144923918-9e8ab762-9c6e-4eb4-bacd-2ca0f81844d8.png)

5) "on a terminé la pose de la verrière de Mr Maréchal a l[a] [??] haute de la"
![Capture d’écran de 2021-12-06 22-08-03](https://user-images.githubusercontent.com/92538363/144924327-e630e23d-a322-4da0-aec8-65f31dd15260.png)

6)"on poursuit la [??] de la facade du transept Sud ansi que de la charpente"
![Capture d’écran de 2021-12-06 22-08-31](https://user-images.githubusercontent.com/92538363/144924412-f3851eb3-013a-4311-a448-d8627b1885dc.png)

7)"la depose des [??] qui flanquent le [pignon] et la corniche formant passage"
![Capture d’écran de 2021-12-06 22-08-52](https://user-images.githubusercontent.com/92538363/144924542-44aafea1-c244-4225-99ab-1f3e5e6ec810.png)

Merci encore, j'ai hâte de savoir ce vous arrivez à lire (mes yeux de médiéviste ne me servent malheureusement guère...)

**Comment by margauxfre** [comment]
Salut,

Je dirai :

1) "dans les noues"

2) je lis aussi "gradins" et juste après on dirait que ce qui est barré est :  ", et"

3) "voligeage"

4) "on a repris par incrustement les portions de tapisserie au dessus des [??]"

7) je lis également "pignon", et pour le premier "pinacles"

Rien ne me vient pour la 5 et la 6...

**Comment by A-Menu** [comment]
Je suis d'accord avec les réponses de Margaux. Pour celui entre la 2 et la 3, ça pourrait être à nouveau "de la flèche formant [gradins] dans les **noues** des combles. pose des verrières"

4. Le dernier mot est peut-être "voussures" ? 

Je sèche également pour le moment pour la 5 et la 6.

**Comment by ElsaVK** [comment]
Merci beaucoup les filles ! On verra si on trouvera l'inspiration pour la 5 et 6 plus tard :)
