### ISSUE TITLE
Numérotation des lignes

### ISSUE THREAD

**Issue by ElsaVK** [PSL-Chartes-HTR-Students/TNAH-2021-Projet-Notre-Dame#9]
Nous en étions au débat du découpage des lignes. Mais j'ai une question toute bête: à quoi cela nous sert exactement d'avoir toutes les mêmes lignes numérotées, du style le folio en n°1, la date en n°2 etc...

**Comment by AnaisMazoue** [comment]
Je pense que ce n'est peut-être pas tant d'avoir toutes exactement la même chose en soi mais plutôt d'avoir quelque chose qui soit cohérent sur chaque page et surtout d'éviter - si possible- les numérotations étranges de ce genre : 
<img width="135" alt="Capture d’écran 2021-12-08 à 18 12 01" src="https://user-images.githubusercontent.com/92513635/145252849-5f67efb0-3b60-409a-97a7-0cc0bcd9bb9b.png">

Pour l'instant, sauf supprimer toutes les lignes et toutes les remettre dans l'ordre voulu, je n'ai pas de solution pour avoir une numérotation correcte donc si l'une de vous a une meilleure idée, je suis preneuse :)

**Comment by margauxfre** [comment]
Comme dit Anaïs, j'ai l'impression que l'important est plutôt d'avoir des numérotations de lignes logiques selon leur ordre d'apparition dans le texte. La numération détermine-t-elle l'ordre d'apparition du texte dans le fichier XML ?

Et pareil pour régler le problème, je ne sais pas comment s'y prendre à part tout numéroter à nouveau (ce qui serait assez long)...

**Comment by margauxfre** [comment]
Salut les filles,

Je pense avoir réussi à régler le problème des numérotations incohérentes (de type ligne 1 qui se retrouve en plein milieu de la page). 

Voilà ce que ça donne de mon côté : 
![Capture d’écran 2022-01-06 à 10 53 33](https://user-images.githubusercontent.com/92535159/148364367-e359a22e-4dcd-450e-a2c1-76b46831d320.png)

Je vous fais un petit tuto : 
Avant de modifier quoi que ce soit : 
1. Exportez la page en texte brut, personnellement la manip m'a fait perdre toutes les transcriptions. J'ai copié/collé ligne par ligne après avoir obtenu la bonne numérotation, c'est assez rapide !

Quand vous êtes sur votre page : 
1. Cliquez sur le bouton pour faire apparaitre la numérotation des lignes

2. Ctrl + A, vous allez alors voir apparaître sur la gauche ceci : 
![Capture d’écran 2022-01-06 à 11 31 45](https://user-images.githubusercontent.com/92535159/148369373-f8069072-7dd9-4bcf-83ab-4d22676e5f75.png)

3. Cliquez sur le 2e bouton (Unlink), celui-ci : 
![Capture d’écran 2022-01-06 à 11 09 43](https://user-images.githubusercontent.com/92535159/148369390-d6caca4a-0364-4e84-9354-1433b1c5c6ae.png)

4. Ne pas cliquer sur Link, sinon la numérotation se fait selon les zones (toute la marge puis toute la zone main, ce que l'on ne veut pas) mais cliquer sur Join selected lines : 
![Capture d’écran 2022-01-06 à 11 22 44](https://user-images.githubusercontent.com/92535159/148368244-b12463a2-3814-4ea8-ae32-9c4aff0701b1.png)

5. Là, vous allez vous retrouver avec une seule ligne pour tout le document (d'où la perte de la transcription je pense). Quelque chose qui ressemble à ça : 
![Capture d’écran 2022-01-06 à 11 24 11](https://user-images.githubusercontent.com/92535159/148368561-eafd4e29-1189-4882-a728-cdfea78ba298.png)

6. Pas de panique, cliquez sur la flèche retour (Undo) en haut à gauche.

- Une première fois, vous allez vous retrouver avec une seule ligne sur votre document : 
![Capture d’écran 2022-01-06 à 11 24 37](https://user-images.githubusercontent.com/92535159/148368788-503f24a3-11a2-446f-8cfd-0725f444ed47.png)

- Cliquez une deuxième fois et vos anciennes lignes reviennent, et numérotées dans le bon ordre : 
![Capture d’écran 2022-01-06 à 11 24 53](https://user-images.githubusercontent.com/92535159/148368880-21f4550f-8069-4dac-90c5-786a022c5ee6.png)

7. Il n'y a plus qu'à copier/coller la transcription (d'où l'importance de récupérer le texte brut pour se faciliter la tâche, sinon on peut aussi la retrouver dans le fichier XML mais c'est un peu plus long).


C'est peut-être un peu artisanal mais ça a fonctionné sur mes 3 pages.
J'espère que c'est clair, faites-moi signe sinon !

**Comment by ElsaVK** [comment]
C'est parfaitement clair, et ça fonctionne super bien ! Merci Margaux ;)

**Comment by AnaisMazoue** [comment]
Merci beaucoup Margaux, je vais tester ça rapidement :)

**Comment by dtsoline** [comment]
Merci Margaux, ça a bien fonctionné !

**Comment by A-Menu** [comment]
Merci beaucoup Margaux pour ce tuto clair et précis ! :)
